name: pull-request-version-tag-check
on: 
  pull_request:
    types:
      - opened
      - edited
      - reopened
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
      - name: Build gemspec
        run: gem build hola.gemspec
      - name: 💎 Extract gemspec info
        id: gemspec_fetch
        uses: bitbrain/gemspec-fetch@1.0.0
        with:
          specfile: hola.gemspec
      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Check gem version has existing git tag
        run: git show-ref --tags --verify --quiet -- "refs/tags/v${{ steps.gemspec_fetch.outputs.version }}" && exit 0 || exit 1