name: Push Create Tag
on:
  push:
    branches:
      - 'main'
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
      - name: Build gemspec
        run: gem build hola.gemspec
      - name: 💎 Extract gemspec info
        id: gemspec_fetch
        uses: bitbrain/gemspec-fetch@1.0.0
        with:
          specfile: hola.gemspec
      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Check gem version has existing git tag
        run: >-
          ( git show-ref --tags --verify --quiet -- "refs/tags/v${{ steps.gemspec_fetch.outputs.version }}" && exit 1 )
          || 
          ( git tag "v${{ steps.gemspec_fetch.outputs.version }}" && git push origin "v${{ steps.gemspec_fetch.outputs.version }}" )
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: ruby
          package-name: hola-gem
          version-file: "lib/hola/version.rb"
      - name: Publish to GPR
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
          OWNER: ${{ github.repository_owner }}