name: Push Create Tag
on:
  push:
    branches:
      - 'main'
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: ruby
          package-name: hola-gem
          version-file: "lib/hola/version.rb"
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - name: Create tag for version
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git tag ${{ steps.release.outputs.tag_name }} || true
          git push origin ${{ steps.release.outputs.tag_name }}
      - uses: ruby/setup-ruby@v1
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish to GPR
        if: ${{ steps.release.outputs.release_created }}
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
          OWNER: ${{ github.repository_owner }}